# Generated by Django 3.0.8 on 2020-07-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cmt_all',
            field=models.CharField(default='TEST', max_length=2024),
        ),
    ]
