# Generated by Django 3.0.8 on 2020-08-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200729_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='File',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/'),
        ),
    ]
