# Generated by Django 3.0.8 on 2020-07-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(default='uploads/', upload_to='uploads/% Y/% m/% d/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/'),
        ),
    ]
