# Generated by Django 3.0.8 on 2020-07-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200721_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(default='uploads/', upload_to='uploads/'),
        ),
    ]
