# Generated by Django 3.0.8 on 2020-07-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200721_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='test',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='test/polls/pic_folder'),
        ),
    ]
