# Generated by Django 3.0.8 on 2020-07-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200721_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(default='polls/uploads/', upload_to='polls/uploads/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='test',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='polls/pic_folder'),
        ),
    ]
