# Generated by Django 3.0.8 on 2020-07-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20200721_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(default='media/uploads/', upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='test',
            field=models.ImageField(default='media/None/no-img.jpg', upload_to='media/pic_folder'),
        ),
    ]
