# Generated by Django 3.0.8 on 2020-07-22 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200721_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 22, 11, 50, 12, 186174, tzinfo=utc), verbose_name='date published'),
        ),
    ]
