# Generated by Django 3.0.8 on 2020-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20200722_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmt_all',
            field=models.CharField(default='', max_length=2024),
        ),
    ]
