# Generated by Django 3.0.8 on 2020-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200722_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmt_all',
            field=models.CharField(default=' ', max_length=2024),
        ),
    ]
