# Generated by Django 3.0.8 on 2020-07-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200722_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmt_all',
            field=models.CharField(default='None', max_length=2024),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='None'),
        ),
    ]
