# Generated by Django 3.0.8 on 2020-07-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20200722_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='Content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='cmt_all',
            new_name='Emb_html',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='file',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='test',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='Pub_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user',
            new_name='Title',
        ),
    ]
