# Generated by Django 3.0.8 on 2020-07-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20200723_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Ip_log',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
