# Generated by Django 3.0.8 on 2020-07-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_comment_ip_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='User_agent',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
