# Generated by Django 3.0.8 on 2020-07-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20200724_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Content',
            field=models.TextField(default='Empty'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Emb_html',
            field=models.CharField(max_length=2024, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='File',
            field=models.FileField(null=True, upload_to='media/uploads/'),
        ),
    ]
