# Generated by Django 3.0.8 on 2020-07-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20200727_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Emb_html',
            field=models.CharField(blank=True, max_length=2024, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='File',
            field=models.FileField(blank=True, default='media/None/', null=True, upload_to='media/uploads/'),
        ),
    ]
